### ISSUE TITLE
Show the number of digits and align numbers to the right

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-scan#62]
Looking at the tokens of an account, balance amounts are not show with decimal points and numbers are not aligned to the right.

Follow the link below:

https://testnet.ccdscan.io/?dcount=1&dentity=account&daddress=36Z8i8wkGbA2tKmrRgXrofvbTbV68KCfJD1nAVSMYJJBKPo7mw

![image.png](https://images.zenhubusercontent.com/6284893f971a3daf4db6e569/a0adef47-4eb6-43c6-8f20-4664fe3b0512)

**Comment by SRConcordium** [comment]
The issue is not completed fixed in Stagenet, observed couple of issues -
https://stagenet.ccdscan.io/accounts?dcount=1&dentity=account&daddress=4sH15AxjthA9DYhCux3aVUtPMemD1oJCL4WFiUXcJKqAeeQ9oc  
1) Decimal points are still missing from the balance values and 
2) Amount is right aligned but header text "Balance" is not aligned above the values, heading should be right above the values. Refer screenshot below - 
![image](https://github.com/Concordium/concordium-scan/assets/113599042/ede86abc-cbaf-4dd4-84d8-412543e5ceb6)

**Comment by parv0888** [comment]
@SRConcordium 
The decimals that need to be shown on the UI are fetched from the Tokens Metadata URL. If the Metadata URL is not valid then the decimals cannot be shown. Which is the case here since the metadata url is 
https://some.example/token/FF16A0F62F17E96C274DB1343EE6A236756D87AB8A88C7989A1CBE90D030A3F4

**Comment by abizjak** [comment]
@parv0888 I agree that this is the correct fallback. The issue with the `balance` location is a valid one, so that should be fixed.

**Comment by SRConcordium** [comment]
Decimal representation for the tokens are shown OK as verified in Testnet CCDScan for account address, 45Dp7jhi7kmQbapb7LHnDju1y4R3u4YXYusPBcw8cmZw7MgTeU with contract indexes - 3501, 3497 and 3504 (refer attached screenshot). The header misalignment issue is still need fixing.
![image](https://github.com/Concordium/concordium-scan/assets/113599042/591f9850-4759-4fb2-91bf-4d8f503e0be6)

**Comment by parv0888** [comment]
![image](https://github.com/Concordium/concordium-scan/assets/1246947/88c05f46-162a-4640-89da-d914d0e5d1e4)

**Comment by parv0888** [comment]
> @parv0888 I agree that this is the correct fallback. The issue with the `balance` location is a valid one, so that should be fixed.

Raised PR for the comment
https://github.com/Concordium/concordium-scan/pull/79

![image](https://github.com/Concordium/concordium-scan/assets/1246947/d8ce8f6e-4dd7-49c2-8021-df042d6c32c6)

**Comment by SRConcordium** [comment]
Verified in Testnet, the header text is right aligned now -
![image](https://github.com/Concordium/concordium-scan/assets/113599042/758e3e8d-8b37-4502-a577-88316b213286)

**Comment by schwartz-concordium** [comment]
Verified mainnet
